export const BUY_VANILLA_CAKE = 'BUY_VANILLA_CAKE';
export const BUY_PINEAPPLE_CAKE = 'BUY_PINEAPPLE_CAKE';
export const BUY_CHOCO_CAKE = 'BUY_CHOCO_CAKE';


export const ADD_VANILLA_CAKE = 'ADD_VANILLA_CAKE';
export const ADD_PINEAPPLE_CAKE = 'ADD_PINEAPPLE_CAKE';
export const ADD_CHOCO_CAKE = 'ADD_CHOCO_CAKE';